# Generated by Django 6.0.3 on 2026-03-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("opcao_a", models.CharField(max_length=100)),
                ("opcao_b", models.CharField(max_length=100)),
                ("opcao_c", models.CharField(max_length=100)),
                ("opcao_d", models.CharField(max_length=100)),
                ("resposta_correta", models.CharField(max_length=1)),
            ],
        ),
    ]
