# Generated by Django 6.0.3 on 2026-03-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="numero",
        ),
    ]
